### ISSUE TITLE
[REQUEST] Disallow rtp radius

### ISSUE THREAD

**Issue by jeffry1829** [Kubajsa/randomTp#43]
Currently, this plugin can only rtp player in a given radius.
However, it's good to have a setting to disallow rtp in a given radius.

For example, for tier-2 rtp. I don't want player to be teleported to the region of tier-1.
```
one:
  enabled: true
  border: 100000
  price: 0
  title: "§7Newbie"
  material: COAL_BLOCK
two:
  enabled: true
  border: 107500
  disallow-radius: 100000
  price: 300
  title: "§fAdventurer"
  material: IRON_BLOCK
```
The setting disallow-radius can prevent tier-2 rtp teleport player to tier-1 region.
